name: Client Node CI

on: [push]

jobs:
  build-test-matrix:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm test
        working-directory: ./client/
        env:
          CI: true
  build-docker-test:
    name: build and test in docker
    needs: [build-test-matrix]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build the Docker image
        run: docker build . --file ./client/Dockerfile.dev --tag laflash/docker-complex
      - name: Test in Docker image
        run: docker run -e CI=true laflash/docker-complex npm run test

  publish-to-dockerhub:
    name: Publish to Docker-Hub
    needs: [build-docker-test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: laflash/docker-complex-client
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          context: ./client
          tag: '0.1.1'
