name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file ./client/Dockerfile.dev --tag laflash/docker-complex
    - name: Test in Docker image
      run: docker run -e CI=true laflash/docker-complex npm run test
  
  test:
    needs: [build]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
