name: Worker Node CI

  on: [push]

  jobs:
    build-test:
      name: build and test
      runs-on: ubuntu-latest

      strategy:
        matrix:
          node-version: [8.x, 10.x, 12.x]

      steps:
        - uses: actions/checkout@v1
        - name: Use Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v1
          with:
            node-version: ${{ matrix.node-version }}
        - name: npm install and test
          run: |
            npm install
            npm test
          working-directory: ./worker/
          env:
            CI: true

    build-docker-test:
      name: build and test in docker
      needs[build-test]
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v1
        - name: Build the Docker image
          run: docker build . --file ./worker/Dockerfile.dev --tag laflash/docker-complex
        - name: Test in Docker image
          run: docker run -e CI=true laflash/docker-complex npm run test

    publish-to-dockerhub:
      name: Publish to Docker-Hub
      needs: [build-test]
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@master
        - name: Publish to Registry
          uses: elgohr/Publish-Docker-Github-Action@master
          with:
            name: laflash/docker-complex-worker
            username: ${{ secrets.DOCKER_USER }}
            password: ${{ secrets.DOCKER_PASSWORD }}
            context: ./worker
            tag: '0.1.0'